spring.application.name=pet-care
server.port=8081

# PostgreSQL Konfigurace
spring.datasource.url=jdbc:postgresql://localhost:5433/nnpia
spring.datasource.username=nnpia
# Heslo zabezpe?eno pomocí environmentální prom?nné DB_PASSWORD
spring.datasource.password=${DB_PASSWORD:nnpia}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# H2 Console (vypnutá pro produk?ní/postgres b?h)
spring.h2.console.enabled=false

# Bezpe?nostní JWT klí? vyta?ený z kódu do konfigurace
jwt.secret=${JWT_SECRET:mojeVelmiTajneHesloKtereJeDostatecneDlouhe123456789}
jwt.expiration.ms=86400000

# Konfigurace pro Groq Cloud
openai.api.url=https://api.groq.com/openai/v1/chat/completions
openai.api.key=${GROQ_API_KEY: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}